import { db } from "@workspace/db";
import {
  usersTable, printersTable, listingsTable, ordersTable, reviewsTable
} from "@workspace/db/schema";

async function seed() {
  if (process.env.NODE_ENV === "production") {
    console.log("⛔ Seed script is disabled in production. Exiting.");
    process.exit(0);
  }
  console.log("Seeding database...");

  // Users
  const [alice, bob, carol, dan, eva] = await db.insert(usersTable).values([
    {
      username: "printmaster_alice",
      displayName: "Alice Chen",
      email: "alice@example.com",
      bio: "Professional 3D printing enthusiast with 5 years of experience. Specializing in high-detail resin prints and functional prototypes. Based in San Francisco.",
      avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=alice",
      role: "seller",
      location: "San Francisco, CA",
      shopName: "Alice's Print Shop",
      shopMode: "both",
      platformFeePercent: 10,
      defaultShippingCost: 7.5,
      totalPrints: 347,
      totalOrders: 412,
      rating: 4.9,
      reviewCount: 89,
    },
    {
      username: "makerlabs_bob",
      displayName: "Bob Martinez",
      email: "bob@example.com",
      bio: "Industrial designer turned 3D printing service provider. My shop specializes in custom enclosures, mechanical parts and artistic sculptures. Let's bring your ideas to life!",
      avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=bob",
      role: "seller",
      location: "Austin, TX",
      shopName: "MakerLabs Bob",
      shopMode: "open",
      platformFeePercent: 10,
      defaultShippingCost: 9,
      totalPrints: 892,
      totalOrders: 1041,
      rating: 4.7,
      reviewCount: 234,
    },
    {
      username: "carol_designs",
      displayName: "Carol Williams",
      email: "carol@example.com",
      bio: "Architect and 3D printing artist. I create architectural models, custom home decor, and artistic installations. Precision and aesthetics are my passion.",
      avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=carol",
      role: "both",
      location: "New York, NY",
      shopName: "Carol Designs Studio",
      shopMode: "catalog",
      platformFeePercent: 10,
      defaultShippingCost: 12,
      totalPrints: 156,
      totalOrders: 178,
      rating: 4.8,
      reviewCount: 47,
    },
    {
      username: "buyer_dan",
      displayName: "Dan Thompson",
      email: "dan@example.com",
      bio: "Hardware startup founder always looking for rapid prototyping services. Love working with talented print makers!",
      avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=dan",
      role: "buyer",
      location: "Seattle, WA",
      totalPrints: 0,
      totalOrders: 28,
    },
    {
      username: "eva_maker",
      displayName: "Eva Rodriguez",
      email: "eva@example.com",
      bio: "Hobbyist turned professional. I print miniatures, tabletop game pieces, and custom figurines with incredible detail.",
      avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=eva",
      role: "seller",
      location: "Miami, FL",
      shopName: "Eva's Mini Factory",
      shopMode: "catalog",
      platformFeePercent: 10,
      defaultShippingCost: 6.5,
      totalPrints: 2341,
      totalOrders: 2891,
      rating: 4.95,
      reviewCount: 512,
    },
  ]).returning();

  // Printers
  await db.insert(printersTable).values([
    {
      userId: alice.id,
      equipmentCategory: "printing_3d",
      name: "Elegoo Saturn 4 Ultra",
      technology: "MSLA",
      brand: "Elegoo",
      model: "Saturn 4 Ultra",
      buildVolume: "218.88x122.88x220mm",
      materials: ["Standard Resin", "ABS-like Resin", "Water-washable Resin", "Tough Resin"],
      layerResolutionMin: 0.01,
      layerResolutionMax: 0.1,
      pricePerHour: 12.00,
      pricePerGram: 0.15,
      isActive: true,
      description: "High-resolution MSLA resin printer for ultra-detailed prints. Perfect for miniatures, jewelry, and precision parts.",
      imageUrl: "/images/abstract-printer.png",
      totalJobsCompleted: 347,
    },
    {
      userId: bob.id,
      equipmentCategory: "printing_3d",
      name: "Bambu Lab X1 Carbon",
      technology: "FDM",
      brand: "Bambu Lab",
      model: "X1 Carbon",
      buildVolume: "256x256x256mm",
      materials: ["PLA", "PETG", "ABS", "TPU", "PA", "PC", "ASA", "PVA"],
      layerResolutionMin: 0.05,
      layerResolutionMax: 0.35,
      pricePerHour: 8.50,
      pricePerGram: 0.08,
      isActive: true,
      description: "Multi-material capable high-speed FDM printer. Excellent for functional parts, enclosures, and large prototypes.",
      imageUrl: "/images/abstract-printer.png",
      totalJobsCompleted: 892,
    },
    {
      userId: carol.id,
      equipmentCategory: "printing_3d",
      name: "Formlabs Form 3+",
      technology: "SLA",
      brand: "Formlabs",
      model: "Form 3+",
      buildVolume: "145x145x185mm",
      materials: ["Standard Resin", "Rigid Resin", "Flexible Resin", "Castable Resin", "Dental Resin"],
      layerResolutionMin: 0.025,
      layerResolutionMax: 0.1,
      pricePerHour: 18.00,
      pricePerGram: 0.25,
      isActive: true,
      description: "Professional-grade SLA printer with smooth surface finish. Ideal for architectural models and artistic pieces.",
      imageUrl: "/images/abstract-printer.png",
      totalJobsCompleted: 156,
    },
    {
      userId: bob.id,
      equipmentCategory: "printing_3d",
      name: "Prusa MK4",
      technology: "FDM",
      brand: "Prusa",
      model: "MK4",
      buildVolume: "250x210x220mm",
      materials: ["PLA", "PETG", "ASA", "ABS", "Flex"],
      layerResolutionMin: 0.05,
      layerResolutionMax: 0.3,
      pricePerHour: 6.00,
      pricePerGram: 0.06,
      isActive: true,
      description: "Reliable workhorse FDM printer. Great value for everyday functional prints.",
      imageUrl: "/images/abstract-printer.png",
      totalJobsCompleted: 445,
    },
    {
      userId: eva.id,
      equipmentCategory: "printing_3d",
      name: "Phrozen Sonic Mega 8K S",
      technology: "MSLA",
      brand: "Phrozen",
      model: "Sonic Mega 8K S",
      buildVolume: "330x185x300mm",
      materials: ["Standard Resin", "ABS-like Resin", "Plant-based Resin"],
      layerResolutionMin: 0.01,
      layerResolutionMax: 0.05,
      pricePerHour: 15.00,
      pricePerGram: 0.18,
      isActive: true,
      description: "Large-format 8K resin printer. Perfect for highly detailed miniatures at scale.",
      imageUrl: "/images/abstract-printer.png",
      totalJobsCompleted: 2341,
    },
    {
      userId: bob.id,
      equipmentCategory: "woodworking",
      toolOrServiceType: "Table saw",
      name: "DeWalt DWE7491 Jobsite Table Saw",
      technology: "other",
      brand: "DeWalt",
      model: "DWE7491",
      buildVolume: "32½\" rip capacity",
      materials: ["Dimensional lumber", "Plywood", "MDF"],
      layerResolutionMin: null,
      layerResolutionMax: null,
      pricePerHour: 55,
      pricePerGram: null,
      isActive: true,
      description: "Precision rip and crosscuts for furniture and enclosure work.",
      imageUrl: "/images/abstract-printer.png",
      totalJobsCompleted: 120,
    },
  ]).returning();

  // Listings
  await db.insert(listingsTable).values([
    {
      sellerId: alice.id,
      title: "Custom Mechanical Phone Stand",
      description: "Fully adjustable phone stand with rotating base and cable management. Print-in-place hinges, no assembly required.",
      category: "Electronics & Gadgets",
      tags: ["phone stand", "cable management", "print-in-place", "functional"],
      imageUrl: "/images/model-placeholder-1.png",
      basePrice: 24.99,
      shippingCost: 5.99,
      estimatedDaysMin: 3,
      estimatedDaysMax: 5,
      material: "PETG",
      color: "Black",
      orderCount: 87,
    },
    {
      sellerId: alice.id,
      title: "D&D Miniature Set (5 figures)",
      description: "Set of 5 high-detail dungeon and dragons miniatures. Warrior, Mage, Rogue, Cleric, and Dragon. 28mm scale.",
      category: "Gaming & Miniatures",
      tags: ["miniature", "dnd", "tabletop", "fantasy"],
      imageUrl: "/images/model-placeholder-2.png",
      basePrice: 49.99,
      shippingCost: 7.99,
      estimatedDaysMin: 5,
      estimatedDaysMax: 8,
      material: "Standard Resin",
      color: "Natural",
      orderCount: 143,
    },
    {
      sellerId: carol.id,
      title: "Architectural Scale Model Base",
      description: "1:100 scale architectural model base plate with terrain features. Custom sizes available on request.",
      category: "Architecture & Design",
      tags: ["architecture", "scale model", "terrain", "professional"],
      imageUrl: "/images/model-placeholder-1.png",
      basePrice: 89.99,
      shippingCost: 14.99,
      estimatedDaysMin: 7,
      estimatedDaysMax: 14,
      material: "Rigid Resin",
      color: "White",
      orderCount: 22,
    },
    {
      sellerId: eva.id,
      title: "Fantasy Dungeon Tile Set",
      description: "Modular dungeon tile system with 20 unique tiles including corridors, rooms, doors and special features.",
      category: "Gaming & Miniatures",
      tags: ["dungeon tiles", "modular", "tabletop", "terrain"],
      imageUrl: "/images/model-placeholder-2.png",
      basePrice: 74.99,
      shippingCost: 8.5,
      estimatedDaysMin: 6,
      estimatedDaysMax: 10,
      material: "Standard Resin",
      color: "Stone Gray",
      orderCount: 512,
    },
    {
      sellerId: eva.id,
      title: "Warhammer Space Marine Squad",
      description: "Set of 10 space marine miniatures in battle poses. Highly detailed armor and weapons. Pre-supported files.",
      category: "Gaming & Miniatures",
      tags: ["warhammer", "space marine", "miniature", "sci-fi"],
      imageUrl: "/images/model-placeholder-1.png",
      basePrice: 64.99,
      shippingCost: 8.5,
      estimatedDaysMin: 5,
      estimatedDaysMax: 9,
      material: "ABS-like Resin",
      color: "Natural",
      orderCount: 389,
    },
    {
      sellerId: bob.id,
      title: "Custom Enclosure / Case",
      description: "Custom-designed enclosure for electronics projects. Provide your dimensions and we'll design and print the perfect case.",
      category: "Electronics & Gadgets",
      tags: ["enclosure", "case", "electronics", "custom"],
      imageUrl: "/images/model-placeholder-2.png",
      basePrice: 34.99,
      shippingCost: 6.5,
      estimatedDaysMin: 4,
      estimatedDaysMax: 7,
      material: "PLA",
      color: "Various",
      orderCount: 201,
    },
  ]);

  // Orders
  const [o1, o2] = await db.insert(ordersTable).values([
    {
      buyerId: dan.id,
      sellerId: alice.id,
      title: "D&D Miniature Set (5 figures)",
      notes: "Please print in natural resin, I'll paint them myself",
      material: "Standard Resin",
      color: "Natural",
      quantity: 2,
      unitPrice: 49.99,
      platformFee: 10.00,
      shippingCost: 0,
      totalPrice: 109.98,
      status: "delivered",
      shippingAddress: "123 Main St, Seattle, WA 98101",
    },
    {
      buyerId: dan.id,
      sellerId: bob.id,
      title: "Custom Electronics Enclosure",
      fileUrl: "/uploads/enclosure_v2.stl",
      notes: "Need this for a Raspberry Pi project. Dimensions: 120x80x40mm",
      material: "PETG",
      color: "Black",
      quantity: 3,
      unitPrice: 34.99,
      platformFee: 10.50,
      shippingCost: 0,
      totalPrice: 115.47,
      status: "printing",
      shippingAddress: "456 Tech Ave, Seattle, WA 98102",
    },
  ]).returning();

  // Reviews
  await db.insert(reviewsTable).values([
    {
      orderId: o1.id,
      reviewerId: dan.id,
      revieweeId: alice.id,
      rating: 5,
      comment: "Absolutely stunning quality! Alice's prints are incredibly detailed and arrived well-packaged. Will definitely order again!",
    },
    {
      orderId: o1.id,
      reviewerId: alice.id,
      revieweeId: dan.id,
      rating: 5,
      comment: "Great buyer, clear requirements and fast payment. A pleasure to work with!",
    },
  ]);

  console.log("✅ Database seeded successfully!");
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
