# Cloudflare Pages configuration

name = "print3d"
compatibility_date = "2024-01-01"

pages_build_output_dir = "dist"

[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

[build.environment]
NODE_VERSION = "20"

[build.processing]
skip_type_checking = true

[build.ignore]
gitignore = [".gitignore"]
ignore = ["lib/**", "../lib/**"]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[vars]
ENVIRONMENT = "production"
